Refactor input/output
zmap/zdns pull request #129
Opened 2017-09-11 14:05 UTC by thereallogani

This allows domain inputs and result outputs to be handled in a more
modular way. Just add iohandlers to define what will populate the input
and output channels. This would allow a workaround to issues like #127.

2018-03-03 18:32 UTC, zakird approved these changes
This looks good to me offhand. Asking @justinbastress to take a second look and make sure he's also cool with the change.

2018-03-03 18:42 UTC, justinbastress commented on iohandlers/file/file.go
> +		f, err = os.OpenFile(h.filepath, os.O_WRONLY|os.O_CREATE, 0666)
0666? Any reason other users need write permission?

2018-03-05 13:53 UTC, justinbastress requested changes
I think the only critical changes would be the 0644->0666 mode, and ensuring that the streams get closed / signalled properly even in case of a panic.

2018-03-05 13:53 UTC, justinbastress commented on interface.go
> +	FeedChannel(in chan<- interface{}, wg *sync.WaitGroup, zonefileInput bool) error
Would be helpful to have the args described

2018-03-05 13:53 UTC, justinbastress commented on interface.go
> +var inputs map[string]InputHandler
Since this is shared throughout the zdns module, maybe rename to `inputHandlers`/`outputHandlers` or something even more specific?

2018-03-05 13:53 UTC, justinbastress commented on iohandlers/file/file.go
> +	close(in)
defer `close`/`Done`, in case there is an unexpected panic?

2018-03-05 13:53 UTC, justinbastress commented on iohandlers/file/file.go
> +		f, err = os.OpenFile(h.filepath, os.O_WRONLY|os.O_CREATE, 0666)
This is 0644 in the old `doOutput` -- any reason this needs to be writable by everyone?

2018-03-05 13:53 UTC, justinbastress commented on iohandlers/file/file.go
> +	(*wg).Done()
Does `(*wg).Done()` need to be deferred in case of an unexpected panic?

2018-03-05 19:43 UTC, justinbastress approved these changes

2018-03-08 15:54 UTC, merged