Follow CNAMES on iterative lookups
zmap/zdns pull request #397
Opened 2024-07-16 15:43 UTC by phillip-stephens

WIP
Resolves #347 

## Note on DNAMES
This PR notably does not handle DNAMES. I have yet to find a cloud provider that would let me setup a DNAME to do testing, and without that I'd just be stabbing in the dark at an implementation. I've looked at:
- Google Cloud DNS
- Cloudflare
- Azure

That can come in a future PR.

## Description

- Bring the logic from ALookups module into all iterative lookups.
- Add a flag to _disable_ this behavior: `--no-follow-cnames`

## Testing

I found 3 domains that use CNAMES. I couldn't add a CNAME chain to `zdns-testing.com` for repeatable tests because Google Cloud "packs" the CNAME's + A records into a single answer:
```
$ dig -t A cname-stop1.zdns-testing.com            
...
;; ANSWER SECTION:
cname-stop1.zdns-testing.com. 300 IN    CNAME   cname-stop2.zdns-testing.com.
cname-stop2.zdns-testing.com. 300 IN    CNAME   cname-stop3.zdns-testing.com.
cname-stop3.zdns-testing.com. 300 IN    CNAME   zdns-testing.com.
zdns-testing.com.       300     IN      A       3.4.5.6
zdns-testing.com.       300     IN      A       1.2.3.4
zdns-testing.com.       300     IN      A       2.3.4.5

```
Therefore, testing with Google Cloud doesn't work.

`echo "www.wwno.org\nwww.wander-plus.com\nwww.microjpm.com" | ./zdns A --iterative`

main Repo - Note how only CNAMES are returned
```
{"data":{"answers":[{"answer":"trvlbuddy.myshopify.com.","class":"IN","name":"www.wander-plus.com","ttl":3600,"type":"CNAME"}],"protocol":"udp","resolver":"97.74.103.44:53"},"name":"www.wander-plus.com","status":"NOERROR","timestamp":"2024-07-16T15:43:02Z"}
{"data":{"answers":[{"answer":"grove1.prod.npr.psdops.com.","class":"IN","name":"www.wwno.org","ttl":1800,"type":"CNAME"}],"protocol":"udp","resolver":"64.125.77.13:53"},"name":"www.wwno.org","status":"NOERROR","timestamp":"2024-07-16T15:43:02Z"}
{"data":{"answers":[{"answer":"microjpm.webnode.page.","class":"IN","name":"www.microjpm.com","ttl":3600,"type":"CNAME"}],"protocol":"udp","resolver":"144.217.207.158:53"},"name":"www.microjpm.com","status":"NOERROR","timestamp":"2024-07-16T15:43:03Z"}
```

Phillip/347-cnames
```

```

2024-07-16 20:03 UTC, phillip-stephens commented
@zakird I hit the `build-and-large-scan-test` too many times so now it's timing out. Other than that, this is ready for review, passing the tests I can think of.

2024-07-18 16:37 UTC, zakird requested changes

2024-07-18 16:37 UTC, zakird commented on src/cli/cli.go
> +	rootCmd.PersistentFlags().BoolVar(&GC.ShouldFollowCNAMEs, "follow-cnames", true, "Follow CNAMEs/DNAMEs in the iterative lookup process, not applicable to non-iterative lookups")
Why isn't this applicable to non-iterative lookups? Shouldn't we follow the name there too if that's what we get back? You could use `alookup` in non-iterative mode, so I think this is a step backwards in terms of functionality.

2024-07-18 16:40 UTC, zakird commented on src/cli/worker_manager.go
> +	config.ShouldFollowCNAMEs = gc.ShouldFollowCNAMEs
This is named inconsistent with other options, would remove the "Should" prefix

2024-07-18 16:42 UTC, zakird commented
While many servers do support CNAME Synthesis, I think it would be best to directly support DNAME's since synthesis was primarily designed for backwards compatibility and I think that researchers will want to know if they were actually just following a DNAME.

2024-07-18 17:03 UTC, phillip-stephens commented on src/cli/cli.go
> +	rootCmd.PersistentFlags().BoolVar(&GC.ShouldFollowCNAMEs, "follow-cnames", true, "Follow CNAMEs/DNAMEs in the iterative lookup process, not applicable to non-iterative lookups")
I was under the impression that in non-iterative mode we leave all resolution decisions up to the name server in question. We just return whatever it gives us.

But what you're describing sounds valid as well, and the user could figure out what queries we made (if we followed a CNAME) by looking at the trace, so this does seem like strictly better functionality.

2024-07-18 17:03 UTC, phillip-stephens commented
Sounds good, I'll add DNAME support and CNAME following on non-iterative queries!

2024-07-18 17:05 UTC, zakird commented on src/cli/cli.go
> +	rootCmd.PersistentFlags().BoolVar(&GC.ShouldFollowCNAMEs, "follow-cnames", true, "Follow CNAMEs/DNAMEs in the iterative lookup process, not applicable to non-iterative lookups")
The intent of the `alookup` module was that it _did_ do that unlike the plain `A` lookup, which returns the raw response.

2024-07-22 21:55 UTC, phillip-stephens commented
@zakird When you have a chance, this is ready for review. I've updated the PR description, we're following DNAMEs now and I've tested external lookups.

2024-07-22 21:57 UTC, phillip-stephens commented
I figure I'll wait to get rid of `alookup` until we have #353 done and can perform `A` and `AAAA` at the same time.

2024-07-23 00:45 UTC, zakird commented
It looks like 
```
    "protocol": "",
    "resolver": ""
```

Are empty in the new code, despite being there in the old one. Can you look into?

2024-07-23 14:17 UTC, phillip-stephens commented
> It looks like
> 
> ```
>     "protocol": "",
>     "resolver": ""
> ```
> 
> Are empty in the new code, despite being there in the old one. Can you look into?

@zakird This definitely was the case with an older version of the code, can you run `git pull` and try with latest since I can't reproduce with the latest code.

```
echo "cloudflare.com" | ./zdns --local-addr "171.67.71.210" --name-servers "1.1.1.1" A
{"data":{"additionals":[{"flags":"","type":"EDNS0","udpsize":1232,"version":0}],"answers":[{"answer":"104.16.133.229","class":"IN","name":"cloudflare.com","ttl":253,"type":"A"},{"answer":"104.16.132.229","class":"IN","name":"cloudflare.com","ttl":253,"type":"A"}],"protocol":"udp","resolver":"1.1.1.1:53"},"name":"cloudflare.com","status":"NOERROR","timestamp":"2024-07-23T14:17:15Z"}

$ echo "cloudflare.com" | ./zdns A --iterative --local-addr "171.67.71.210" --name-servers "1.1.1.1"
{"data":{"answers":[{"answer":"104.16.133.229","class":"IN","name":"cloudflare.com","ttl":300,"type":"A"},{"answer":"104.16.132.229","class":"IN","name":"cloudflare.com","ttl":300,"type":"A"}],"protocol":"udp","resolver":"162.159.0.33:53"},"name":"cloudflare.com","status":"NOERROR","timestamp":"2024-07-23T14:17:02Z"}
```

2024-07-23 17:48 UTC, zakird commented
I'm not sure that I follow. This is what's in the body of the PR:

```{"data":{"answers":[{"answer":"trvlbuddy.myshopify.com.","class":"IN","name":"www.wander-plus.com","ttl":3600,"type":"CNAME"}],"protocol":"udp","resolver":"97.74.103.44:53"},"name":"www.wander-plus.com","status":"NOERROR","timestamp":"2024-07-16T15:43:02Z"}
{"data":{"answers":[{"answer":"grove1.prod.npr.psdops.com.","class":"IN","name":"www.wwno.org","ttl":1800,"type":"CNAME"}],"protocol":"udp","resolver":"64.125.77.13:53"},"name":"www.wwno.org","status":"NOERROR","timestamp":"2024-07-16T15:43:02Z"}
{"data":{"answers":[{"answer":"microjpm.webnode.page.","class":"IN","name":"www.microjpm.com","ttl":3600,"type":"CNAME"}],"protocol":"udp","resolver":"144.217.207.158:53"},"name":"www.microjpm.com","status":"NOERROR","timestamp":"2024-07-16T15:43:03Z"}``` which does have this? If mainline doesn't do this, I don't follow how we ended up with that output.

2024-07-23 18:02 UTC, phillip-stephens commented
Ohhhh, thought you were seeing this behavior on the branch. You're correct, I forgot to update the PR description. Just updated!

2024-07-31 04:25 UTC, zakird approved these changes

2024-07-31 04:25 UTC, merged