Print per-second summary statistics detailing a scan, similar to ZMap
zmap/zdns pull request #473
Opened 2024-11-11 20:07 UTC by phillip-stephens

2024-11-12 15:55 UTC, zakird requested changes
I don't think it's OK to make this not disable'able or not redirectable. I also don't think that it's OK to put these on `stdout` since it precludes piping ZDNS into another program. These should be able to be turned on and off and should be printed to stderr or a file. 

The most useful thing in ZMap to make sure a scan looks good is hitrate, which you can't actually quite get here. Can we get the same thing here. When calculating hitrate I would include both `NOERROR` and `NXDOMAIN` because both are a successful response from the DNS server.

2024-11-12 16:11 UTC, phillip-stephens commented
Yep all seems reasonable! Will make those changes

2024-11-19 19:25 UTC, zakird commented on src/cli/iohandlers/status_handler.go
> +			s := fmt.Sprintf("%02dh:%02dm:%02ds; %d domains scanned; %.02f domains/sec.; %.01f%% success rate; %s\n",
I think that should be `names` not `domains`. I also think you could get rid of the `.` after sec.

2024-11-19 19:26 UTC, zakird commented on src/cli/iohandlers/status_handler.go
> +	s := fmt.Sprintf("%02dh:%02dm:%02ds; Scan Complete, no more input. %d domains scanned; %.02f domains/sec.; %.01f%% success rate; %s\n",
I think you can drop `, no more input`.  Would switch `domain` to `name` here.

2024-11-24 22:36 UTC, zakird approved these changes

2024-11-24 22:36 UTC, merged