Alookup
zmap/zdns pull request #77
Opened 2016-10-10 14:27 UTC by zakird

2016-10-10 14:27 UTC, zakird commented
This should fix the bad logic in the `alookup` module.

2016-10-10 18:12 UTC, umbernhard reviewed
Looks alright to me, thought admittedly I'm probably not the right person to be making this call.

2016-10-10 18:12 UTC, umbernhard commented
Also you'll have to pull master before you merge

2016-10-10 22:51 UTC, dadrian requested changes

2016-10-10 22:51 UTC, dadrian commented on modules/alookup/alookup.go
> +func (s *Lookup) doLookupProtocol(name string, nameServer string, dnsType uint16, searchSet *map[string][]miekg.Answer, origName string, depth int) ([]string, zdns.Status, error) {
Don't pass a map by pointer, just pass it by value. Maps are reference values. See http://stackoverflow.com/questions/14928826/passing-pointers-to-maps-in-golang

2016-10-11 18:15 UTC, dadrian approved these changes

2016-10-11 18:15 UTC, merged