Add the option of including a timestamp in every output json
zmap/zdns pull request #89
Opened 2017-01-10 01:25 UTC by paul-pearce

Adds `--timestamp` which will include a golang time.Time in every
output object. If ``--timestamp` is not set, the field is omitted.

Usage:
```
$ echo "example.com" | ./zdns A
{"name":"example.com","status":"NOERROR","data":{"answers":[{"ttl":49854,"type":"A","name":"example.com","answer":"93.184.216.34"}],"additionals":[],"authorities":[],"protocol":"udp"}}
```

```
$ echo "example.com" | ./zdns A --timestamp
{"name":"example.com","status":"NOERROR","timestamp":"2017-01-09T17:05:54.706439267-08:00","data":{"answers":[{"ttl":49626,"type":"A","name":"example.com","answer":"93.184.216.34"}],"additionals":[],"authorities":[],"protocol":"udp"}}
```

Let me answer some questions you're going to ask.

* Paul, why did you make `Timestamp` of type `*time.Time` instead of `time.Time`
** Because `time.Time` can not be `empty`, meaning `omitempty` does not work right
* Paul, why do you create a variable and then take it's address (`now`) instead of just taking the address of `time.Now()`
** Because that goes against the spec, despite the fact that `time.Now()` can't return `nil`
* Paul,  why are you doing this in doLookup() instead of miekg.DoLookup(), which would be closer to the wire time. 
** Because the config information is not passed that deep into the depths of zdns.

2017-01-10 01:26 UTC, zakird commented
fwm. @dadrian please confirm this is teh right way of doing this in golang

2017-01-10 01:27 UTC, paul-pearce commented
Personally, I'd argue for this being enabled by default.

2017-01-10 01:29 UTC, zakird commented
I am not fundamentally opposed to that.

2017-01-10 19:49 UTC, dadrian commented
This seems like a fine way to handle it being optional. However, I see no reason not to make this default and non-configurable, which means we could just use a `time.Time` instead of a pointer.

2017-01-10 19:50 UTC, zakird commented
I'm alright with it just being included.
On Tue, Jan 10, 2017 at 1:49 PM David Adrian <notifications@github.com>
wrote:

> This seems like a fine way to handle it being optional. However, I see no
> reason not to make this default and non-configurable, which means we could
> just use a time.Time instead of a pointer.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/zmap/zdns/pull/89#issuecomment-271678666>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAMSUNbdbqC4dw9VlUCNyrq7vCV4we_Sks5rQ-DDgaJpZM4Le7fb>
> .
>

2017-01-10 19:50 UTC, dadrian commented
That being said, this is a different time format than every other Z* project.

2017-01-10 19:51 UTC, zakird commented
Can someone paste what it is? Is it not 8601?
On Tue, Jan 10, 2017 at 1:50 PM David Adrian <notifications@github.com>
wrote:

> That being said, this is a different time format than every other Z*
> project.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/zmap/zdns/pull/89#issuecomment-271678894>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAMSUKVTdht8dpQ1bUVn013Uqhs0COZGks5rQ-D6gaJpZM4Le7fb>
> .
>

2017-01-10 19:51 UTC, dadrian commented
`2017-01-09T17:05:54.706439267-08:00`

2017-01-10 19:53 UTC, zakird commented
What's the ZGrab one? That level of precision doesn't seem necessary
offhand.
On Tue, Jan 10, 2017 at 1:51 PM David Adrian <notifications@github.com>
wrote:

> 2017-01-09T17:05:54.706439267-08:00
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/zmap/zdns/pull/89#issuecomment-271679218>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAMSUMwybU9lb48OoNyz2Ma8Uo0N4UUcks5rQ-FDgaJpZM4Le7fb>
> .
>

2017-01-10 19:56 UTC, dadrian commented
ZGrab is `"timestamp": "2017-01-10T14:55:34-05:00"`

2017-01-10 19:57 UTC, zakird commented
I vote have zdns match zgrab
On Tue, Jan 10, 2017 at 1:56 PM David Adrian <notifications@github.com>
wrote:

> ZGrab is "timestamp": "2017-01-10T14:55:34-05:00"
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/zmap/zdns/pull/89#issuecomment-271680440>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAMSUKQOQB2H7CQTz-kEwPKzjGiMEY14ks5rQ-JTgaJpZM4Le7fb>
> .
>

2017-01-10 20:01 UTC, dadrian requested changes

2017-01-10 20:01 UTC, dadrian commented on conf.go
>  }
Let's change the output format to match ZGrab.

If you're not familiar with how to do this "cleanish" in Golang, you're going to have to write a custom `func (r *Result) MarshalJSON() ([]byte, error)` function to handle the formatting. I'd probably put this in a new file called `json.go`. You'll need to create a private auxillary type that has a `Timestamp string`, and manually convert using `time.Format`. Then just `return json.Marshal(&auxStruct)`.

2017-01-11 00:04 UTC, paul-pearce commented
Changes:

-Include timestamps by default
-Change to RFC3339 timestamps
-Store the the timestamp as RFC3339 instead of time.Time. I did this as a tradeoff to avoid a custom JSONMarshal. Given that the timestamp is generated in the same code block as the call to marshal, it seemed like overkill/overengineering to implement a custom marshaller to keep the true time.Time type for ~3 lines of code. If we need to use the timestamp in the future for anything other than printing, I'll volunteer to extend it with a custom marshaller.

2017-01-11 00:57 UTC, dadrian approved these changes

2017-01-11 00:59 UTC, merged